### ISSUE TITLE
mac  can't open qtox.app

### ISSUE THREAD

**Issue by childeYin** [RowenStipe/qTox-OSX#3] opened 2015-11-26 10:02 UTC
mac 10.10.5 (14F27)

Check with the developer to make sure qTox works with this version of OS X. You may need to reinstall the application. Be sure to install any available updates for the application and OS X.

Click Report to see more detailed information and send a report to Apple.

somebody let me must tell you the fault of qtox on mac, he  insist and  told me , you must install qtox on you mac, because qtox is very very nice, so can you help me?

**Comment by RowenStipe** [comment] 2015-11-26 15:31
Can you get me more information than that? I'm not sure what the issue might be as that's the same version of OS X I used to build the program.

You could try running it in terminal; `Finder > Applications > Utilities > Terminal` to get any extra information about why the program fails.

**Comment by wfdd** [comment] 2015-11-26 17:44
This is a duplicate of #2.

**Comment by RowenStipe** [comment] 2015-11-26 17:48
My inexperience with OSX development is showing @_@;

**Comment by childeYin** [comment] 2015-11-27 03:58
yes, i found it is same with #2  ;
Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/libsodium.13.dylib
  Referenced from: /Applications/qTox.app/Contents/Frameworks/libtoxcore.0.dylib
  Reason: Incompatible library version: libtoxcore.0.dylib requires version 17.0.0 or later, but libsodium.13.dylib provides version 16.0.0

**Comment by kitech** [comment] 2015-11-27 04:21
Update the libsodium mannually?

**Comment by RowenStipe** [comment] 2015-11-27 05:51
Okay after working out the ways in which I fail. I have a patch release that should be working: https://github.com/RowenStipe/qTox-OSX/releases/download/PATCH-1.0.1.2/qTox-OSX-PATCH-1.0.1.2.dmg

Please let me know if this works or not for you.

**Comment by childeYin** [comment] 2015-11-27 07:30
oh, it's work, thank you very much,

**Closed as completed** 2015-11-27 09:19 UTC
Labels: bug, duplicate
